apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: spotlink-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spotlink-web
  template:
    metadata:
      labels:
        app: spotlink-web
    spec:
      nodeSelector:
        env: dev
      containers:
      - name: web
        image: 440744234807.dkr.ecr.us-east-1.amazonaws.com/spotlink/web:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: spotlink-dev
spec:
  selector:
    app: spotlink-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  namespace: spotlink-dev
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod" # Ajusta según tu issuer
spec:
  rules:
  - host: web.spotlink.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-service
            port:
              number: 80
  tls:
  - hosts:
    - web.spotlink.app
    secretName: web-prod-tls
