name: Build and Deploy to EKS

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-develop

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: your-region

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker image
      run: |
        docker build -t spotlink/web:develop .
        docker tag spotlink/web:develop ${{ steps.login-ecr.outputs.registry }}/spotlink/web:develop

    - name: Push Docker image
      run: |
        docker push ${{ steps.login-ecr.outputs.registry }}/spotlink/web:develop

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'develop'

    - name: Set Kubeconfig context
      run: |
          echo "${{ secrets.KUBECONFIG_DEV }}" > kubeconfig
          export KUBECONFIG=$(pwd)/kubeconfig
          kubectl config use-context $(kubectl config current-context)
      shell: bash

    - name: Deploy to Kubernetes
      env:
        KUBECONFIG: ${{ github.workspace }}/kubeconfig
      run: |
          kubectl apply -f k8s/dev/
      shell: bash
